import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NextAuthSessionProvider from "@/components/atoms/auth/NextAuthSessionProvider";
import ProgressBar from "@/components/atoms/progress/ProgressBar";
import Footer from "@/components/organisms/footer/Footer";
import Header from "@/components/organisms/header/Header";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "TechUnity",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-[screen]`}
			>
				<NextAuthSessionProvider>
					<Header />
				</NextAuthSessionProvider>
				<ProgressBar>
					{children}
					<Toaster />
				</ProgressBar>

				<Footer />
			</body>
		</html>
	);
}
