name: actions

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js のセットアップ
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 依存関係をインストール
      - name: Install dependencies
        run: npm ci

      # 4. テスト実行
      - name: Test
        run: npm run test

      # 5. カバレッジ取得（必要に応じてコメントアウト等で管理）
      - name: Coverage
        run: npm run coverage

      - name: Check Coverage
        run: |
          # テストが実行されたファイルのみのカバレッジを取得
          FILES_COVERED=$(jq '[. | to_entries[] | select(.value.lines.total > 0) | .value.lines.pct] | length' coverage/coverage-final.json)

          # テストが実行されたファイルがゼロの場合は 100% に設定（エラー回避）
          if [[ "$FILES_COVERED" -eq 0 ]]; then
              echo "⚠️ No files were tested, assuming 100% coverage."
              COVERAGE=100
          else
              COVERAGE=$(jq '[. | to_entries[] | select(.value.lines.total > 0) | .value.lines.pct] | add / length' coverage/coverage-final.json)
          fi

          echo "Coverage: $COVERAGE%"

          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
              echo "❌ Coverage is below 80%! (Current: $COVERAGE%)"
              exit 1
          else
              echo "✅ Coverage is above 80%. (Current: $COVERAGE%)"
          fi
